name: Trigger auto deployment for ayu-api-gateway

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'api-gateway/**'
    - '.github/workflows/ayu-api-gateway-AutoDeployTrigger-3bd5cf74-4005-4459-8f37-6b17f05d1584.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AYUAPIGATEWAY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AYUAPIGATEWAY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AYUAPIGATEWAY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/api-gateway 
          registryUrl: ayulanka.azurecr.io
          registryUsername: ${{ secrets.AYUAPIGATEWAY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AYUAPIGATEWAY_REGISTRY_PASSWORD }}
          containerAppName: ayu-api-gateway
          resourceGroup: CTSE_Assignment
          imageToBuild: ayulanka.azurecr.io/ayu-api-gateway:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


